app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

app/__init__.py
from flask import Flask
from config import Config

app = Flask(__name__)
app.config.from_object(Config)

from app import routes, db

if __name__ == '__main__':
    app.run()

app/routes.py
from app import app
from app.forms import LoginForm
from flask import render_template, flash, redirect, url_for, request, make_response, Blueprint
from app import db

bp = Blueprint('koan', __name__,
               template_folder='templates',
               static_folder='static')

def _solvable(idx, answered, dependencies):
    if idx not in dependencies:
        return True
    for dep in dependencies[idx]:
        if dep not in answered:
            return False
    return True

def makequestions(questions, answered, dependencies):
    todo = []
    todo_temp = []
    done = []
    done_temp = []
    for i in questions:
        if not _solvable(i['id'], answered, dependencies):
            continue
        if i['id'] in answered:
            done_temp.append(i)
            if len(done_temp) == 3:
                done.append(done_temp)
                done_temp = []
        else:
            todo_temp.append(i)
            if len(todo_temp) == 3:
                todo.append(todo_temp)
                todo = []
    if len(todo_temp) > 0:
        todo.append(todo_temp)
    if len(done_temp) > 0:
        done.append(done_temp)
    return todo, done

def render_index(team):
    questions = db.questions()
    answered = set(db.getanswered(team))
    dependencies = db.dependencies()
    points = db.getpoints(team)
    todo, done = makequestions(questions, answered, dependencies)
    return make_response(
        render_template('index.html', team=team, points=points,
                        question_lists=todo,
                        done_question_lists=done))
    
def render_login(message):
    return make_response(render_template('login.html', message=message))

def handle_login(request):
    if request.method == 'POST':
        team = request.form.get('team')
        if team is not None:
            response = render_index(team)
            response.set_cookie('team', team)
            return response
    return None

@bp.route('/index', methods=['GET', 'POST'])
@bp.route('/', methods=['GET', 'POST'])
def index():
    index = handle_login(request)
    if index is not None:
        return index

    team = request.cookies.get('team')
    if team == '' or team is None:
        return login()

    return render_index(team)

@bp.route('/login', methods=['GET', 'POST'])
def login():
    index = handle_login(request)
    if index is not None:
        return index
    return render_login('Sign In')

@bp.route('/signout', methods=['GET'])
def sign_out():
    response = redirect(url_for('koan.login'))
    response.set_cookie('team', '', expires=0)
    return response

@bp.route('/question', methods=['GET', 'POST'])
def question():
    team = request.cookies.get('team')
    if team == '' or team is None:
        return redirect(url_for('koan.login'))

    team = request.cookies.get('team')
    question = db.getquestion(request.args.get('question_id'))

    guess = ''
    if question['id'] in db.getanswered(team):
        guess = question['answer']
    elif request.method == 'POST':
        guess = request.form.get('guess')

    return render_template('question.html',
                           question=questionpage(question, guess, team))

def questionpage(question, guess, team):
    if (guess != ''):
        question['guess'] = guess
        if (guess.rstrip().lower() == question['answer'].rstrip().lower()):
            db.correct(team, question)
            question['judgment'] = 'correct'
            question['judgmentColor'] = 'green'
        else:
            question['judgment'] = 'incorrect'
            question['judgmentColor'] = 'red'

    return question
                           
app.register_blueprint(bp, url_prefix='/koan')

app/templates/base.html
<!doctype html>

<meta name="viewport" content="width=device-width, initial-scale=1.0">

<html>
    <head>
      <!-- Compiled and minified CSS -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <!-- Compiled and minified JavaScript -->
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
      <link rel="stylesheet" href='static/style.css' />
      <title>Koan</title>
    </head>
    <body>
      <div class="topnav">
        <a href="{{ url_for('koan.index') }}">Home</a>
        <a href="{{ url_for('koan.sign_out') }}">Sign Out</a>
      </div>
        <hr>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}
    </body>
</html>

app/templates/index.html
{% extends "base.html" %}

{% block title %} Index {% endblock %}

{% block content %}
</head>
<body>
  <h3>Questions available for <b>{{ team }}</b></h3>
  You currently have {{ points }} point(s). Answer questions to get more!
  {% for question_list in question_lists %}
  <div class="row">
    {% for question in question_list %}
    <div class="col s12 m4">
      <a href = "{{ url_for('koan.question', question_id=question.id) }}">
	<div class="card pink darken-1">
	  <div class="card-content white-text">
	    <h5><b> {{ question.name }} </B></h5>
	    This is worth {{ question.points }} point(s).
	  </div>
	</div>
      </a>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
  {% for question_list in done_question_lists %}
  <div class="row">
    {% for question in question_list %}
    <div class="col s12 m4">
      <a href = "{{ url_for('koan.question', question_id=question.id) }}">
	<div class="card pink lighten-3">
	  <div class="card-content white-text">
	    <h5> {{ question.name }} </h5>
	    You've already solved this!
	  </div>
	</div>
      </a>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
</body>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<h3>Welcome to Koan!</h3>
Koan was a coding competition app made for the <a href="https://www.meetup.com/Chicago-Tech-Interviews">Chicago Tech Interviews</a> meetup, but we've left it up for anyone to play with :) 
<br><br>
To start, we'll need a name for you or the team you're playing with. Use the same team name on multiple devices to share work!
    <form action="" method="post" novalidate>
      <p>Team Name <input type = "text" name = "team" /></p>
      <p><input type = "submit" value = "submit" /></p>
    </form>
{% endblock %}

app/templates/question.html
{% extends "base.html" %}

{% block content %}
<body>
  <div>
    <h2> {{ question.name }}</h2>
    <span>
      <b> Points: </b> {{ question.points }} <br><br>
	  <span style="width:99%; word-wrap:break-word; display:inline-block;">
	    {{ question.question }}
	  </span>
      
    </span>
    <br><br>
    {% if question.guess %}
    <h5> Your guess <b>{{ question.guess }}</b> was
      <b><font color={{question.judgmentColor}}>{{question.judgment}}!</font></b></h5>
    {% endif %}
    {% if question.judgment != 'correct' %}
    <form action="" method="post" novalidate>
      <p> Your guess: <input type = "text" name = "guess" /></p>
      <p><input type = "submit" value = "Submit" /></p>
    </form>
    {% endif %}
  </div>
  {% if question.judgment == 'correct' %}
  <h5><a href="{{ url_for('koan.index') }}"> Try another one?</a></h5>
  {% endif %}
  <br>
      
</body>
{% endblock %}